### PR TITLE
feat: Added AEM Asset Selector sidekick configs

### PR DESCRIPTION
**Pull request by sdmcraft**
Test URLs:
- Before: https://main--wknd--hlxsites.hlx.page/drafts/satyam/aem-asset-selector
- After: https://aem-assets--wknd--hlxsites.hlx.page/drafts/satyam/aem-asset-selector

### CODE REVIEW

**Comment by sdmcraft** [comment]
@dylandepass , @auniverseaway  tagging you to get some initial feedback on this. I recorded the flow here for reference https://adobe-my.sharepoint.com/:v:/p/satyam/EZ8xJJwsM-FGoir3RGFzPKsBjED9-PfBGp9uPwD_rRKw3w?e=QcesOa

**Comment by dylandepass** [comment]
@sdmcraft This is great start. 

Couple thoughts..

I wonder if we could run this off franklin and bypass the need for the netlify app? That would be ideal I think.

I had some issues connecting to prod. Seems to always want to default to stage, even from their configuration screen? Were you able to connect to prod? We have a prod instance we'd like to use for the wknd, so would be nice to connect to that.

I'm surprised this is the login experience they provided. This should ideally use the discovery service to allow users to pick from a list of available repositories instead of requiring all the configuration.

**Comment by sdmcraft** [comment]
> @sdmcraft This is great start.
> Couple thoughts..

Thanks for taking out the time to review @dylandepass .

> I wonder if we could run this off franklin and bypass the need for the netlify app? That would be ideal I think.

Yes after the latest changes, netlify app isn't needed anymore. Everything is now hosted within Franklin itself. I think you would be getting redirected to the netlify app as that's set as the default redirect url in the IMS client that I created for this. I am facing some issues with IMS auth flow redirections.  I am not allowed to specify the wknd site as the `default redirect_url` in the IMSS which I [have raised here](https://cq-dev.slack.com/archives/C12TA9N8N/p1677836333029399). For now the workaround is to close and reopen the sidekick palette. On reopening, when you click "Sign In" again , the asset selector should open up correctly as this time you would be already logged in and would not get redirected to the netlify app.

> I had some issues connecting to prod. Seems to always want to default to stage, even from their configuration screen? Were you able to connect to prod? We have a prod instance we'd like to use for the wknd, so would be nice to connect to that.

There were a few issues connecting with prod which I fixed yesterday. It should work with prod as well now. The word doc where the configurations are [set is here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BF6910347-9CED-4E49-9309-A4911987CE92%7D&file=aem-asset-selector.docx&action=default&mobileredirect=true) . You can try setting the AEM Wknd env co-ordinates in it or share with me and I can try it out.

> I'm surprised this is the login experience they provided. This should ideally use the discovery service to allow users to pick from a list of available repositories instead of requiring all the configuration.

Hm..that's a great point. This is something I needs to check with the Asset selector team. Basically I am following the setup [documented here](https://git.corp.adobe.com/CQ/assets-selectors/tree/main/packages/%40assets/selectors/examples/vanilla-js) with some tweaks to make it work within Franklin. I'll check about the repository picker experience.

**Comment by sdmcraft** [comment]
@dylandepass , thanks from guiding me on this. Also copying @davidnuescheler for his inputs. On the IMS SSO login experience, I worked with the asset selector team and now specifying the AEM details etc. is not longer needed. The only configuration needed is the IMS org. This is also temporary till https://jira.corp.adobe.com/browse/ASSETS-22140. 
[I recorded a short video to explain the flow](https://adobe-my.sharepoint.com/:v:/p/satyam/EZWMtOdHmE5Jl_tDWYqN2iIB1JUXfSAmNqqRF5-8oGzOOg?e=MGxWnT).

**Comment by dylandepass** [comment]
@sdmcraft I did speak with @davidnuescheler about this earlier this week. I think the biggest blocker to putting this in right now is the requirement on having to manage adding sales folks to the org with the Assets Essentials instance for WKND. I think in a typical franklin site the login requirement is totally fine and expected. This repo though is meant to be more of sales tool so we want to minimize demo friction as much as possible.

We discussed a couple options.

1. The ideal solution is to build a service that could fetch a valid token and pass that to the assets selector bypassing the need for anyone to login or having to add people to an org.
2. The less ideal solution is to figure out if it's possible to somehow allow anyone with an @adobe.com account to login to the Assets essentials instance.
3. The last option would be to manage adding sales folks to the org manually.

Any thoughts on that @sdmcraft? 

@davidnuescheler mentioned that the AEM Assets team is currently working on a more "Franklinized" version of Assets which might be another area of exploration.

**Comment by sdmcraft** [comment]
On the login requirement, I think the easiest path is to create a group in admin console and grant it access to wknd AEM instance. And then upload a list of users in csv format (if we can manage to create such a list) via bulk upload in admin console.  That way all of them get access by virtue of their group membership.

> AEM Assets team is currently working on a more "Franklinized" version of Assets which might be another area of exploration.

Indeed. I think there's some work being done for content-lake and definitely worth exploring.  Though in this specific prototype, the primary intent is to show the value by being able to use assets which the users may already have in their traditional AEM based enterprise repositories.

**Comment by sdmcraft** [comment]
Since `wknd` is a special use-case, I added a "without-IMS" flow which uses a pre-fetched token thereby totally eliminating the requirement to login via IMS flow. You can give it a try by clicking on `WKND` button in https://aem-assets--wknd--hlxsites.hlx.page/drafts/satyam/aem-asset-selector

**Comment by sdmcraft** [comment]
Closing this for lack of any progress.

**Pull request closed without merging**
